USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TourOperator SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Direction SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DirectionOperatorCombination ADD CONSTRAINT
	FK_DirectionOperatorCombination_Direction FOREIGN KEY
	(
	DirectionID
	) REFERENCES dbo.Direction
	(
	DirectionID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.DirectionOperatorCombination ADD CONSTRAINT
	FK_DirectionOperatorCombination_TourOperator FOREIGN KEY
	(
	OperatorID
	) REFERENCES dbo.TourOperator
	(
	TourOperatorID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.DirectionOperatorCombination SET (LOCK_ESCALATION = TABLE)
GO
COMMIT