USE [GT]

GO

SET ANSI_PADDING ON


GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_Passport] ON [dbo].[CustomerDetails]
(
	[Passport] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO