USE [GT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE TourCustomerEdit
	@TourID INT, @CustomerDetailsID ID_List READONLY
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	DECLARE @msg NVARCHAR(1024)
	BEGIN TRY
		BEGIN TRANSACTION
			DELETE FROM TourCustomerDetails WHERE TourID = @TourID

			INSERT INTO TourCustomerDetails
			SELECT @TourID, ID FROM @CustomerDetailsID
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF XACT_STATE() = -1 ROLLBACK;
		THROW
	END CATCH
END