USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.AirOperator
	(
	AirOperatorID int NOT NULL,
	AirOperator nvarchar(50) NOT NULL,
	Country nvarchar(50) NULL,
	URL nvarchar(255) NULL,
	Login nvarchar(50) NULL,
	Password nvarchar(50) NULL,
	Contract bit NOT NULL,
	Tel varchar(50) NULL,
	Email nvarchar(50) NULL,
	website nvarchar(50) NULL,
	FB nvarchar(50) NULL,
	skype nvarchar(50) NULL,
	OtherContacts nvarchar(512) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.AirOperator ADD CONSTRAINT
	PK_AirOperator PRIMARY KEY CLUSTERED 
	(
	AirOperatorID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.AirOperator SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
