USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Client
	(
	ClientID int NOT NULL IDENTITY (1, 1),
	ClientFullName nvarchar(50) NOT NULL,
	ClientContacts nvarchar(512) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Client ADD CONSTRAINT
	PK_Client PRIMARY KEY CLUSTERED 
	(
	ClientID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Client SET (LOCK_ESCALATION = TABLE)
GO
COMMIT