USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AdvertiseType SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Advertise
	(
	AdvertiseID int NOT NULL IDENTITY (1, 1),
	CreationDate date NOT NULL,
	Fee decimal(12, 0) NOT NULL,
	ForYear smallint NOT NULL,
	ForMonth tinyint NOT NULL,
	TypeID int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Advertise ADD CONSTRAINT
	PK_Advertise PRIMARY KEY CLUSTERED 
	(
	AdvertiseID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Advertise ADD CONSTRAINT
	FK_Advertise_AdvertiseType FOREIGN KEY
	(
	TypeID
	) REFERENCES dbo.AdvertiseType
	(
	TypeID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Advertise SET (LOCK_ESCALATION = TABLE)
GO
COMMIT