USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.HotelBooking
	(
	HotelBookID int NOT NULL IDENTITY (1, 1),
	CreationDate date NOT NULL,
	StartDate date NOT NULL,
	EndDate date NOT NULL,
	Price decimal(12, 0) NOT NULL,
	Cost decimal(12, 0) NULL,
	CustomerID int NOT NULL,
	AdultCount tinyint NOT NULL,
	ChildCount tinyint NOT NULL,
	BabyCount tinyint NOT NULL,
	ChildYearsComment nvarchar(255) NULL,
	FoodTypeID int NOT NULL,
	Transfer bit NOT NULL,
	PrePayID int NULL,
	OperatorID int NULL,
	PaymaetDeathLine date NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.HotelBooking ADD CONSTRAINT
	PK_HotelBooking PRIMARY KEY CLUSTERED 
	(
	HotelBookID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.HotelBooking SET (LOCK_ESCALATION = TABLE)
GO
COMMIT