USE GT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE AirportAdd
	@AirportName NVARCHAR(255),@CountryID INT,@City NVARCHAR(255),@Code NVARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO Airport (AirportName,CountryID,City,Code) VALUES(@AirportName,@CountryID,@City,@Code)
END
GO