USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.PrePayment
	(
	PrePeyID int NOT NULL IDENTITY (1, 1),
	CreationDate date NOT NULL,
	Price decimal(12, 0) NOT NULL,
	NextPayDate date NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PrePayment ADD CONSTRAINT
	PK_PrePayment PRIMARY KEY CLUSTERED 
	(
	PrePeyID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.PrePayment SET (LOCK_ESCALATION = TABLE)
GO
COMMIT