USE [GT]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UtilityType](
	[UtilityTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Utility] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_UtilityType] PRIMARY KEY CLUSTERED 
(
	[UtilityTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO