USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tax
	(
	TaxID int NOT NULL IDENTITY (1, 1),
	CreationDate date NOT NULL,
	Fee decimal(12, 0) NOT NULL,
	ForYear smallint NOT NULL,
	ForMonth tinyint NOT NULL,
	TaxTypeID int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tax ADD CONSTRAINT
	PK_Tax PRIMARY KEY CLUSTERED 
	(
	TaxID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Tax SET (LOCK_ESCALATION = TABLE)
GO
COMMIT