USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.OfficeExponse
	(
	OfficeExponseID int NOT NULL IDENTITY (1, 1),
	CreationDate date NOT NULL,
	Fee decimal(12, 0) NOT NULL,
	ForYear smallint NOT NULL,
	ForMonth tinyint NOT NULL,
	OfficeExponseTypeID int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.OfficeExponse SET (LOCK_ESCALATION = TABLE)
GO
COMMIT