USE GT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OfficeExponseType SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.OfficeExponse ADD CONSTRAINT
	FK_OfficeExponse_OfficeExponseType FOREIGN KEY
	(
	OfficeExponseTypeID
	) REFERENCES dbo.OfficeExponseType
	(
	OfficeExponseTypeID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.OfficeExponse SET (LOCK_ESCALATION = TABLE)
GO
COMMIT