USE GT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE EmployeeAdd
	@FirstName NVARCHAR(50), @LastName NVARCHAR(50)
AS
BEGIN

	SET NOCOUNT ON;
	INSERT INTO Employee (FirstName,LastName) VALUES(@FirstName,@LastName)
END
GO