USE GT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE OtherExpenseTypeUpdate
	@TypeID INT, @TypeName NVARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	UPDATE OtherExpenseType SET TypeName = @TypeName WHERE TypeID = @TypeID
END
GO