USE GT
GO

-- ATTENTION
-- ATTENTION
-- ATTENTION

TRUNCATE TABLE Insurance
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Insurance
	DROP CONSTRAINT FK_Insurance_Customer
GO
ALTER TABLE dbo.Customer SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_Insurance
	(
	InsuranceID int NOT NULL IDENTITY (1, 1),
	CreationDate date NOT NULL,
	StartDate date NOT NULL,
	EndDate date NOT NULL,
	ClientID int NOT NULL,
	Price decimal(12, 0) NOT NULL,
	Cost decimal(12, 0) NULL,
	ReturnableDate date NULL,
	IsMulti bit NOT NULL,
	DaysCount smallint NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_Insurance SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_Insurance ON
GO
IF EXISTS(SELECT * FROM dbo.Insurance)
	 EXEC('INSERT INTO dbo.Tmp_Insurance (InsuranceID, CreationDate, StartDate, EndDate, ClientID, Price, Cost, ReturnableDate)
		SELECT InsuranceID, CreationDate, StartDate, EndDate, ClientID, Price, Cost, ReturnableDate FROM dbo.Insurance WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_Insurance OFF
GO
DROP TABLE dbo.Insurance
GO
EXECUTE sp_rename N'dbo.Tmp_Insurance', N'Insurance', 'OBJECT' 
GO
ALTER TABLE dbo.Insurance ADD CONSTRAINT
	PK_Insurance PRIMARY KEY CLUSTERED 
	(
	InsuranceID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Insurance ADD CONSTRAINT
	FK_Insurance_Customer FOREIGN KEY
	(
	ClientID
	) REFERENCES dbo.Customer
	(
	CustomerID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT